### ISSUE TITLE
SQL Injections and Reinforcement Learning: An Empirical Evaluation of the Role of Action Structure

### ISSUE THREAD

**Issue by manuel-delverme** [Limmen/awesome-rl-for-cybersecurity#1]
Our paper SQL Injections and Reinforcement Learning: An Empirical Evaluation of the Role of Action Structure has a related sql injection env!
https://github.com/manuel-delverme/sql_env
it's pretty fast too, as it's an in memory database an minimal webserver mock

**Comment by Limmen** [comment]
Great! I was not aware. I have added it. Please consider making a pull request next time.
