### ISSUE TITLE
Newer paper in CyBORG environment

### ISSUE THREAD

**Issue by Tudyx** [Limmen/awesome-rl-for-cybersecurity#9]
There is a newer paper presenting CyBORG environment (2021) : https://arxiv.org/abs/2108.09118

As the older paper (2020) contains other illustrations, I think we should keep both

**Comment by manuel-delverme** [comment]
The issue with these papers is that the RL part is really really superficial
>We trained each RL agent for up to 2500 iterations

Is this paper at all useful for people reading the list?

> Availability
Limited access to CybORG will be available for reviewers,
with a public release planned once the scenario library is ex-
panded

There is no link or anything.
I know this is not a place for peer review but the SNR is important for readers

**Comment by Tudyx** [comment]
Without judging the paper itself, but in comparison with the one already linked in the repository it has some advantages: 

- State of the art is more updated
- A description of the Action and the Observation is provided
- Description of the tech stack used for emulation (Metasploit, etc..) is provided

But maybe those improvements are not worth the noise added.
Otherwise we could just replace the current link with the new one and though limiting the noise while benefit of the advantages listed above.

**Comment by Tudyx** [comment]
Yeah I will open one
